(function(){
  "use strict";
  const syncModel=window.HamboardSyncStateModel,repositoryCore=window.HamboardProjectRepository,googleDrive=window.HamboardMobileGoogleDrive;
  if(!syncModel||!repositoryCore)throw new Error("hamboard-mobile-dependencies-unavailable");
  const storage=repositoryCore.createIndexedDbStateStorage({databaseName:"hamboard-mobile",storeName:"state",stateKey:"mobile-core"}),repository=repositoryCore.createProjectRepository({storage,syncModel,clientProfile:"mobile-core"});
  const $=selector=>document.querySelector(selector),listScreen=$("#projectListScreen"),readerScreen=$("#projectReaderScreen"),backButton=$("#mobileBack"),title=$("#mobileTitle"),indicator=$("#syncIndicator"),search=$("#projectSearch"),searchField=$("#projectSearchField"),fileInput=$("#mobileDataFile"),libraryNav=$("#libraryNav"),createNav=$("#createNav"),menuNav=$("#menuNav"),createSheet=$("#createSheet"),mainMenuSheet=$("#mainMenuSheet"),menuSearch=$("#menuSearch"),menuCloud=$("#menuCloud"),cloudSheet=$("#cloudSheet"),cloudMessage=$("#cloudSheetMessage"),cloudConnect=$("#cloudConnect"),cloudDisconnect=$("#cloudDisconnect");
  let activeProjectId="",activeEpisodeId="",query="";
  const clone=value=>typeof structuredClone==="function"?structuredClone(value):JSON.parse(JSON.stringify(value));
  const element=(tag,className,text)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=String(text);return node};
  const safeColor=(value,fallback="#785b9f")=>/^#[0-9a-f]{6}$/i.test(String(value||""))?String(value):fallback;
  const formatDate=value=>{const parsed=Date.parse(String(value||""));return Number.isFinite(parsed)?new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"short",day:"numeric"}).format(parsed):""};
  const allBlocks=unit=>{const result=[],walk=nodes=>(nodes||[]).forEach(node=>{result.push(node);walk(node.children)});for(const stage of unit?.stageDefs||[])walk(unit?.stages?.[stage.id]);return result};
  const projectStats=project=>{const units=project.kind==="long"?(project.episodes||[]):[project],blocks=units.flatMap(allBlocks);return {units:units.length,blocks:blocks.length,completed:blocks.filter(block=>block.completed).length}};
  const scriptLabels={dialogue:"대사",narration:"지문",background:"배경",shot:"구도",page:"페이지",cut:"컷"};
  const cloudErrorMessage=error=>{const text=String(error?.message||error||"");if(text.includes("web-client-id-not-configured"))return "Google 로그인 설정을 불러오지 못했습니다. 배포 설정을 확인해 주세요.";
if(text.includes("secure-origin-required"))return "Google 로그인은 HTTPS 주소에서 사용할 수 있습니다. 현재 IP:1430 개발 주소는 로그인용 보안 주소로 바꿔야 합니다.";if(text.includes("popup_closed")||text.includes("popup-failed"))return "Google 로그인 창이 닫혔습니다. 다시 시도해 주세요.";if(text.includes("access_denied"))return "Google Drive 접근 권한이 허용되지 않았습니다.";if(text.includes("branched-history"))return "클라우드 동기화 기록이 갈라져 있어 PC에서 먼저 동기화 충돌을 해결해야 합니다.";if(text.includes("download-integrity")||text.includes("commit-"))return "클라우드 데이터 검증에 실패했습니다. PC에서 다시 동기화한 뒤 시도해 주세요.";if(text.includes("http-401")||text.includes("reconnect-required"))return "Google 연결이 만료되었습니다. 다시 로그인해 주세요.";return "Google Drive에서 데이터를 불러오지 못했습니다. 네트워크와 로그인 상태를 확인해 주세요."};
  function setIndicator(state,text){indicator.dataset.state=state;indicator.textContent=text}
  function setStatus(message,{action="",run=null}={}){const status=$("#projectStatus");status.replaceChildren(document.createTextNode(message));if(action&&run){const button=element("button","",action);button.type="button";button.onclick=run;status.append(button)}status.hidden=false}
  function hideStatus(){$("#projectStatus").hidden=true}
  function openBottomSheet(sheet){if(sheet)sheet.hidden=false}
  function closeBottomSheet(sheet){if(sheet)sheet.hidden=true}
  function openLibrary(){if(activeProjectId)closeProject();libraryNav.classList.add("active");window.scrollTo({top:0,behavior:"smooth"})}
  function openSearch(){closeBottomSheet(mainMenuSheet);if(activeProjectId)closeProject();searchField.hidden=false;requestAnimationFrame(()=>search.focus())}
  function metaChip(text){return element("span","meta-chip",text)}
  function renderList(){
    const projects=repository.list(),filtered=projects.filter(project=>!query||`${project.title||""} ${project.subtitle||""}`.toLocaleLowerCase("ko").includes(query));
    $("#projectCount").textContent=query?`${filtered.length}개 검색됨`:`${projects.length}개 작품`;
    const host=$("#projectList");host.replaceChildren();
    if(!projects.length){setStatus("동기화된 작품이 아직 없습니다. 현재 단계에서는 JSON 상태나 백업 manifest를 불러와 모바일 표시를 확인할 수 있습니다.",{action:"데이터 파일 불러오기",run:()=>fileInput.click()});return}
    if(!filtered.length){setStatus("검색 결과가 없습니다.");return}hideStatus();
    for(const project of filtered){const stats=projectStats(project),button=element("button","project-card");button.type="button";button.dataset.projectId=String(project.id);button.style.setProperty("--card-color",safeColor(project.color));const color=element("span","project-color"),copy=element("span","project-card-copy"),label=element("span","project-card-label",project.kind==="long"?"장편 작품":"단편 작품"),heading=element("h3","",project.title||"제목 없는 작품"),subtitle=element("p","",project.subtitle||"부제 없음"),meta=element("span","project-card-meta");meta.append(metaChip(project.kind==="long"?`${stats.units}화`:`${(project.stageDefs||[]).length}파트`),metaChip(`${stats.blocks}블록`));if(stats.blocks)meta.append(metaChip(`${stats.completed}/${stats.blocks} 완료`));copy.append(label,heading,subtitle,meta);const arrow=document.createElementNS("http://www.w3.org/2000/svg","svg");arrow.setAttribute("viewBox","0 0 24 24");arrow.setAttribute("class","project-card-arrow");const path=document.createElementNS("http://www.w3.org/2000/svg","path");path.setAttribute("d","m9 18 6-6-6-6");arrow.append(path);button.append(color,copy,arrow);button.onclick=()=>openProject(project.id);host.append(button)}
  }
  function blockElement(block){const card=element("article","block-card"),head=element("div","block-head"),heading=element("h5","",block.title||(block.type==="script"?"제목 없는 스크립트":"제목 없는 블록"));head.append(heading);if(block.completed)head.append(element("span","complete-badge","완료"));card.append(head);if(block.type==="script"){const lines=element("div","script-lines");for(const line of block.scriptBlocks||[]){if(!String(line?.text||"").trim()&&!String(line?.speaker||"").trim())continue;const row=element("div","script-line"),label=element("span","script-line-label",scriptLabels[line.type]||"지문"),body=element("span","");if(line.type==="dialogue"&&line.speaker)body.append(element("span","script-speaker",`${line.speaker} · `));body.append(document.createTextNode(String(line.text||"")));row.append(label,body);lines.append(row)}if(lines.childElementCount)card.append(lines)}else if(block.summary)card.append(element("p","block-text",block.summary));if(block.notes)card.append(element("div","block-notes",block.notes));if((block.children||[]).length){const children=element("div","child-blocks");for(const child of block.children)children.append(blockElement(child));card.append(children)}return card}
  function renderUnit(unit,index=0){const host=$("#projectContent");host.replaceChildren();const heading=element("div","unit-heading"),name=unit.title||`${index+1}화`;heading.append(element("h3","",name));if(unit.subtitle)heading.append(element("p","",unit.subtitle));host.append(heading);for(const stage of unit.stageDefs||[]){const section=element("section","stage-section"),stageHead=element("header","stage-heading"),stripe=element("span","stage-color"),copy=element("div","");stripe.style.setProperty("--stage-color",safeColor(stage.color));copy.append(element("h4","",stage.name||"파트"));if(stage.hint)copy.append(element("p","",stage.hint));stageHead.append(stripe,copy);const blocks=element("div","block-list"),items=Array.isArray(unit.stages?.[stage.id])?unit.stages[stage.id]:[];if(items.length)for(const block of items)blocks.append(blockElement(block));else blocks.append(element("div","empty-stage","등록된 블록이 없습니다."));section.append(stageHead,blocks);host.append(section)}}
  function renderReader(project){
    const stats=projectStats(project);$("#readerKind").textContent=project.kind==="long"?"장편 작품":"단편 작품";$("#readerTitle").textContent=project.title||"제목 없는 작품";$("#readerSubtitle").textContent=project.subtitle||"";$("#readerSubtitle").hidden=!project.subtitle;const meta=$("#readerMeta");meta.replaceChildren(metaChip(`${stats.blocks}개 블록`));if(stats.blocks)meta.append(metaChip(`${stats.completed}개 완료`));if(project.deadline)meta.append(metaChip(`마감 ${project.deadline}`));if(project.updatedAt){const date=formatDate(project.updatedAt);if(date)meta.append(metaChip(`${date} 수정`))}
    const episodes=$("#episodeList");episodes.replaceChildren();if(project.kind==="long"){const list=project.episodes||[];if(!list.length){$("#projectContent").replaceChildren(element("div","status-card","등록된 화가 없습니다."));return}if(!list.some(item=>String(item.id)===activeEpisodeId))activeEpisodeId=String(list[0].id);list.forEach((episode,index)=>{const button=element("button",`episode-button${String(episode.id)===activeEpisodeId?" active":""}`);button.type="button";const stripe=element("span","episode-color");stripe.style.setProperty("--episode-color",safeColor(episode.color));const copy=element("span","episode-copy");copy.append(element("strong","",episode.title||`${index+1}화`),element("span","",episode.subtitle||`${allBlocks(episode).length}개 블록`));button.append(stripe,copy,element("span","episode-number",`${index+1}화`));button.onclick=()=>{activeEpisodeId=String(episode.id);renderReader(project);window.scrollTo({top:0,behavior:"smooth"})};episodes.append(button)});renderUnit(list.find(item=>String(item.id)===activeEpisodeId),list.findIndex(item=>String(item.id)===activeEpisodeId))}else{activeEpisodeId="";renderUnit(project)}
  }
  function openProject(id){const project=repository.get(id);if(!project)return;activeProjectId=String(project.id);activeEpisodeId="";listScreen.hidden=true;readerScreen.hidden=false;backButton.hidden=false;title.textContent=project.title||"작품";libraryNav.classList.remove("active");renderReader(project);history.replaceState({projectId:activeProjectId},"",`#project/${encodeURIComponent(activeProjectId)}`);window.scrollTo(0,0)}
  function closeProject(){activeProjectId="";activeEpisodeId="";readerScreen.hidden=true;listScreen.hidden=false;backButton.hidden=true;title.textContent="보관함";libraryNav.classList.add("active");history.replaceState({},"",location.pathname+location.search);renderList();window.scrollTo(0,0)}
  async function importCanonicalState(source){const canonical=source?.format==="hamboard-cloud-backup"&&source.state?source.state:source?.state&&Array.isArray(source.state.projects)?source.state:source;if(!canonical||!Array.isArray(canonical.projects))throw new Error("mobile-project-state-invalid");const projection=syncModel.projectCanonicalState(canonical,syncModel.CLIENT_PROFILES.mobileCore);await repository.replaceState(projection,{markBaseline:true});indicator.dataset.state="synced";indicator.textContent="불러옴";closeProject();return repository.list()}
  async function applyCloudCommits(commits=[]){for(const commit of commits)await repository.applyCommit(commit);repository.markSynced();indicator.dataset.state="synced";indicator.textContent="동기화";closeProject();return repository.list()}
  function commitTopology(objects=[]){const commits=objects.filter(item=>item?.syncType==="commit"&&item.revision&&String(item.objectKey||"").startsWith("sync/commits/")),byRevision=new Map();for(const item of commits){const revision=String(item.revision);if(byRevision.has(revision))throw new Error("sync-import-duplicate-revision");byRevision.set(revision,item)}const parents=new Set(commits.map(item=>String(item.baseRevision||"")).filter(Boolean)),heads=commits.filter(item=>!parents.has(String(item.revision)));if(!commits.length)return {head:null,path:[]};if(heads.length!==1)throw new Error("sync-import-branched-history");const reverse=[],seen=new Set();let cursor=heads[0];while(cursor){const revision=String(cursor.revision);if(seen.has(revision))throw new Error("sync-import-revision-cycle");seen.add(revision);reverse.push(cursor);const parent=String(cursor.baseRevision||"");if(!parent)break;cursor=byRevision.get(parent);if(!cursor)throw new Error("sync-import-missing-parent")}return {head:heads[0],path:reverse.reverse()}}
  async function readCloudCommit(object){const result=await googleDrive.getSyncObject({remoteObjectId:String(object.remoteObjectId||""),objectKey:String(object.objectKey||""),contentSha256:String(object.contentSha256||""),byteSize:Number(object.byteSize)||0});let commit;try{commit=JSON.parse(String(result.content||""))}catch{throw new Error("sync-commit-json-invalid")}if(commit?.format!=="hamboard-sync-commit"||commit?.formatVersion!==1||commit?.stateSchemaVersion!==1||String(commit.revision||"")!==String(object.revision||"")||String(commit.baseRevision||"")!==String(object.baseRevision||"")||!Array.isArray(commit.changes))throw new Error("sync-commit-header-invalid");const profile=syncModel.clientProfileForCommit(commit),profileId=syncModel.clientProfileId(profile);if(object.clientProfile&&String(object.clientProfile)!==profileId)throw new Error("sync-commit-client-profile-mismatch");syncModel.validateClientChanges(commit.changes,profile);for(const change of commit.changes){if(change?.operation!=="upsert")continue;const bytes=new TextEncoder().encode(JSON.stringify(change.payload)),hash=await googleDrive.sha256Hex(bytes);if(hash!==String(change.payloadSha256||""))throw new Error("sync-commit-payload-hash-mismatch")}commit.clientProfile=profileId;return commit}
  async function syncFromCloud(){if(!googleDrive)throw new Error("google-drive-web-transport-unavailable");setIndicator("busy","불러오는 중");cloudMessage.textContent="PC의 최신 동기화 데이터를 확인하고 있습니다…";const listing=await googleDrive.listSyncObjects();if(listing.truncated)throw new Error("sync-object-list-truncated");const topology=commitTopology(listing.objects||[]);if(!topology.head){setIndicator("synced","연결됨");cloudMessage.textContent="Google Drive에 동기화된 데이터가 아직 없습니다.";return {empty:true,projects:repository.list()}}let projected=syncModel.projectCanonicalState({},syncModel.CLIENT_PROFILES.mobileCore);for(let index=0;index<topology.path.length;index++){cloudMessage.textContent=`동기화 데이터를 불러오는 중입니다. (${index+1}/${topology.path.length})`;const commit=await readCloudCommit(topology.path[index]),result=syncModel.applyCommitToClientState(projected,commit,syncModel.CLIENT_PROFILES.mobileCore);projected=result.state}await repository.replaceState(projected,{markBaseline:true});setIndicator("synced","동기화");cloudMessage.textContent=`최신 데이터 동기화 완료 · 작품 ${repository.list().length}개`;renderList();return {empty:false,revision:String(topology.head.revision),projects:repository.list()}}
  function renderCloudSheet(){const status=googleDrive?.status?.()||{configured:false,connected:false};cloudDisconnect.hidden=!status.connected;cloudConnect.textContent=status.connected?"지금 다시 불러오기":"Google로 로그인";if(status.connected)cloudMessage.textContent="Google Drive에 연결되어 있습니다. PC의 최신 데이터를 다시 확인할 수 있습니다."}
  function openCloudSheet(){renderCloudSheet();cloudSheet.hidden=false}
  function closeCloudSheet(){cloudSheet.hidden=true}
  async function connectAndSync(){cloudConnect.disabled=true;cloudDisconnect.disabled=true;try{const status=googleDrive.status();if(!status.connected)await googleDrive.connect();renderCloudSheet();await syncFromCloud()}catch(error){console.error("모바일 Google Drive 동기화 실패",error);setIndicator("error","오류");cloudMessage.textContent=cloudErrorMessage(error)}finally{cloudConnect.disabled=false;cloudDisconnect.disabled=false}}
  async function start(){try{await repository.load();setIndicator("local",googleDrive?.status().configured?"로그인":"로컬");renderList();const match=location.hash.match(/^#project\/(.+)$/);if(match)openProject(decodeURIComponent(match[1]))}catch(error){console.error("모바일 작품 저장소를 열지 못했습니다.",error);setStatus("모바일 저장소를 열지 못했습니다. 브라우저의 사이트 데이터 설정을 확인해 주세요.")}}
  search.addEventListener("input",()=>{query=search.value.trim().toLocaleLowerCase("ko");renderList()});backButton.onclick=closeProject;libraryNav.onclick=openLibrary;createNav.onclick=()=>openBottomSheet(createSheet);menuNav.onclick=()=>openBottomSheet(mainMenuSheet);$("#createSheetClose").onclick=()=>closeBottomSheet(createSheet);$("#mainMenuClose").onclick=()=>closeBottomSheet(mainMenuSheet);createSheet.onclick=event=>{if(event.target===createSheet)closeBottomSheet(createSheet)};mainMenuSheet.onclick=event=>{if(event.target===mainMenuSheet)closeBottomSheet(mainMenuSheet)};menuSearch.onclick=openSearch;menuCloud.onclick=()=>{closeBottomSheet(mainMenuSheet);openCloudSheet()};indicator.onclick=openCloudSheet;$("#cloudSheetClose").onclick=closeCloudSheet;cloudSheet.onclick=event=>{if(event.target===cloudSheet)closeCloudSheet()};cloudConnect.onclick=connectAndSync;cloudDisconnect.onclick=()=>{googleDrive.disconnect();setIndicator("local","로그인");cloudMessage.textContent="Google Drive 연결을 해제했습니다. 모바일에 내려받은 데이터는 유지됩니다.";renderCloudSheet()};window.addEventListener("popstate",()=>{if(activeProjectId)closeProject()});fileInput.onchange=async()=>{const file=fileInput.files?.[0];fileInput.value="";if(!file)return;try{await importCanonicalState(JSON.parse(await file.text()))}catch(error){console.error("모바일 데이터 불러오기 실패",error);setStatus("파일에서 작품 데이터를 불러오지 못했습니다.",{action:"다시 선택",run:()=>fileInput.click()})}};
  window.HamboardMobileApp=Object.freeze({start,repository,importCanonicalState,applyCloudCommits,syncFromCloud,commitTopology,readCloudCommit,openProject,closeProject,snapshot:()=>repository.snapshot()});
  start();
})();
