[package]
name = "hamboard"
version = "1.0.10"
description = "Hamboard desktop application"
authors = ["Hamboard"]
edition = "2021"

[profile.dev]
debug = 0

[lib]
name = "hamboard_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde_json = "1"
sqlx = { version = "0.8", default-features = false, features = ["sqlite", "runtime-tokio"] }
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-dialog = "2.7.2"
tauri-plugin-fs = "2"
tauri-plugin-notification = "2.3.3"
tauri-plugin-opener = "2"
tauri-plugin-process = "2"
tauri-plugin-sql = { version = "2", features = ["sqlite"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-autostart = "2"

[target.'cfg(target_os = "windows")'.dependencies]
base64 = "0.22.1"
rand = "0.8.7"
reqwest = { version = "0.13.4", default-features = false, features = ["rustls"] }
sha2 = "0.10.9"
url = "2.5.8"
